server:
  port: 80
spring:
  application:
    name: ruiji
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ruiji?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  main:
    banner-mode: off
  redis:
    host: 39.105.115.148
    port: 6379
    password: 123456
    database: 0 #默认提供了16个数据库，0表示0号数据库
    jedis:
      pool: #连接池配置
        max-active: 8 #最大连接数
        max-wait: 1ms #最大阻塞等待时间
        max-idle: 4 #最大空闲连接
        min-idle: 0 #最小空闲连接
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
    banner: false

ruiji:
#  path: /home/project/ruiji/img/
  path: D:/WorkingFile/Java/DATA/Ruiji/img/